# Generated by Django 5.1.1 on 2024-10-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True, upload_to="catalog/img", verbose_name="Изображение"
            ),
        ),
    ]
